services:

  api_db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - ${API_DB_PORT:-3003}:5432
    networks:
      - api_network

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-8082}:8080
    networks:
      - api_network

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    networks:
      - sonarqube_network
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonarqube_network
    volumes:
      - sonar_db:/var/lib/postgresql

volumes:
  sonar_data:
  sonar_logs:
  sonar_db:

networks:
  api_network:
    driver: bridge
  sonarqube_network:
    driver: bridge